language: java

cache:
  directories:
    - $HOME/.m2

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version
  - mvn dependency:resolve-plugins dependency:resolve -e

script: mvn clean verify -e

jdk: oraclejdk7
